-- PARENT_ITEM_ID를 스캔했을 때 ITEM ID 에서 없는 아이템 아이디를 찾아라

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT A.ITEM_ID
    FROM ITEM_TREE AS A
    WHERE NOT EXISTS (
        SELECT *
        FROM ITEM_TREE AS B
        WHERE B.PARENT_ITEM_ID = A.ITEM_ID
    )
)
ORDER BY ITEM_ID DESC


