-- 코드를 입력하세요
SELECT PR.PRODUCT_CODE
      , PR.PRICE * T2.TOTAL_AMOUNT AS SALES
FROM PRODUCT PR
JOIN (
    SELECT OS.PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL_AMOUNT
    FROM OFFLINE_SALE AS OS
    GROUP BY OS.PRODUCT_ID 
) AS T2
ON PR.PRODUCT_ID = T2.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE