
SELECT FR.PRODUCT_ID , FR.PRODUCT_NAME, T1.TOTAL_AMOUNT * FR.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS FR
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE LEFT(PRODUCE_DATE, 7) = '2022-05'
    GROUP BY PRODUCT_ID
) T1
ON FR.PRODUCT_ID = T1.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FR.PRODUCT_ID



