WITH T1(SHIPMENT_ID, FLAVOR, TOTAL_ORDER) 
AS 
(SELECT J.SHIPMENT_ID, J.FLAVOR, SUM(J.TOTAL_ORDER) FROM JULY AS J GROUP BY J.FLAVOR) 

SELECT T2.FLAVOR 
FROM
(
SELECT T1.FLAVOR, (T1.TOTAL_ORDER + F.TOTAL_ORDER) AS TOTAL_ORDER FROM T1
LEFT JOIN FIRST_HALF AS F 
ON T1.FLAVOR = F.FLAVOR
ORDER BY TOTAL_ORDER DESC
LIMIT 3
#ON T1.SHIPMENT_ID = F.SHIPMENT_ID
) T2
